# Game constants
WIDTH, HEIGHT = 1920, 1020
FPS = 30
GAME_NAME = "Battleships"
HALF_WIDTH, HALF_HEIGHT = WIDTH / 2, HEIGHT / 2

# Camera constants
MAX_CAMERA_VEL = 10
CAMERA_VEL_CHANGE = 1
MIN_CAMERA_VEL = 1
MAX_SCALE = 4
MIN_SCALE = 0.4
MAX_GAME_SPEED = 5
SCALE_UP_SPEED = 1.3
SCALE_DOWN_SPEED = 1 / SCALE_UP_SPEED
MAX_SHIPS = 8

